<?php

namespace EshopBundle\Repository;

/**
 * baskets_productsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class baskets_productsRepository extends \Doctrine\ORM\EntityRepository
{
}
