<?php

namespace EshopBundle\Repository;

/**
 * basketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basketsRepository extends \Doctrine\ORM\EntityRepository
{
}
