<?php

namespace EshopBundle\Repository;

/**
 * category_productsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class category_productsRepository extends \Doctrine\ORM\EntityRepository
{
}
