<?php

namespace EshopBundle\Repository;

/**
 * customersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customersRepository extends \Doctrine\ORM\EntityRepository
{
}
