<?php

namespace EshopBundle\Repository;

/**
 * historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historyRepository extends \Doctrine\ORM\EntityRepository
{
}
