<?php

namespace EshopBundle\Repository;

/**
 * products_tagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class products_tagsRepository extends \Doctrine\ORM\EntityRepository
{
}
