<?php

namespace EshopBundle\Repository;

/**
 * tagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tagsRepository extends \Doctrine\ORM\EntityRepository
{
}
