eshop_home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

eshop_dashboard:
    path:     /board
    defaults: { _controller: EshopBundle:Board:board }

eshop_newproduct_view:
    path:     /product/{id}
    defaults: { _controller: EshopBundle:Post:view }

eshop_addproduct:
    path:     /add
    defaults: { _controller: EshopBundle:Post:add }

eshop_editproduct:
    path:     /edit/{id}
    defaults: { _controller: EshopBundle:Post:edit }
    requirements:
            id: \d+

eshop_deleteproduct:
    path:     /delete/{id}
    defaults: { _controller: EshopBundle:Post:delete }
    requirements:
        id: \d+
login:
    pattern:   /login
    defaults:  { _controller: EshopBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

